name: Docker website CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
jobs:
  deploy:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: secrets.DOCKERHUB_TOKEN }}
      - name: Build website image
        run: |
           docker build --platform linux --tag ghcr.io/mates182/prueba:latest -f src/Dockerfile . 
      - name: Publish website image
        run: |
           docker push ghcr.io/mates182/prueba:latest
